version: "3.8"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
  
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: listry
      POSTGRES_USER: listry
      POSTGRES_PASSWORD: listry
    volumes:
      - database:/var/lib/postgresql/data:rw
      - ./database.sql:/docker-entrypoint-initdb.d/db.sql:ro

volumes:
  database: