version: "3.8"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: listry
      DATABASE_USERNAME: listry
      DATABASE_PASSWORD: # TODO: Fill

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: listry
      POSTGRES_USER: listry
      POSTGRES_PASSWORD: # TODO: Fill
    volumes:
      - database:/var/lib/postgresql/data:rw
      - ./database.sql:/docker-entrypoint-initdb.d/db.sql:ro

volumes:
  database: